Vagrant.configure("2") do |config|

    config.vm.box = "base"
    config.vm.box = "geerlingguy/ubuntu2004"
    config.vm.hostname = "app01"
    config.vm.network "private_network", ip: "192.168.56.2"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.provision "shell", path: "provision.sh"
  end